# Generated by Django 4.1.3 on 2022-12-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vuqes.bankaccount'),
        ),
    ]
