# Generated by Django 4.1.3 on 2022-12-21 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vuqes', '0002_alter_transaction_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vuqes.bankaccount', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма перевода'),
        ),
    ]
