# Generated by Django 4.1.3 on 2022-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0004_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
