# Generated by Django 4.1.3 on 2022-12-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0005_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuqes.bankaccount', verbose_name='Получатель'),
        ),
    ]
