# Generated by Django 4.1.3 on 2022-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0006_rename_user_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_success',
            field=models.BooleanField(null=True),
        ),
    ]
