# Generated by Django 4.1.3 on 2022-12-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0007_transaction_is_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
