# Generated by Django 4.1.3 on 2022-12-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuqes', '0008_rename_receiver_transaction_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sent',
            new_name='recipient',
        ),
    ]
